[project]
name = "rag-againts-the-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bm25s>=0.3.10",
    "fire>=0.7.1",
    "nltk>=3.10.3",
    "numpy>=2.4.6",
    "pydantic>=2.13.4",
    "pystemmer>=3.1.0",
    "vllm>=0.27.1; sys_platform == 'linux'",
]

[tool.uv]
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]
